name: reverse-proxy

services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:  bun run index.ts
    ports:
      - "8080:8080"
      - "80:80"
    network_mode: bridge  # Corrected spacing and syntax
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Fixed the path for docker.sock
      - ./src:/app  # Corrected indentation for volumes
